lambda:
  ses:
    fromEmail: ${AWS_SES_FROM_EMAIL}
    fromName: ${SES_FROM_NAME}
    region: ${AWS_REGION}
  sqs:
    region: ${AWS_REGION}
    queues:
      email: ${SQS_EMAIL_QUEUE_URL}
      deadLetter: ${SQS_DEAD_LETTER_QUEUE_URL}

services:
  accountUrl: ${SERVICES_ACCOUNT_URL}




logging:
  level: ${LOG_LEVEL}
  rootLevel: ${ROOT_LOG_LEVEL}
  packageLevels:
    com.fp: ${LOG_LEVEL}
    software.amazon.awssdk: WARN
    software.amazon.awssdk.request: WARN