package com.fp.sqs.email;


import com.fp.sqs.Message;
import com.fp.sqs.MessageType;

/**
 * Email Message DTO for SQS communication.
 * Contains only business data, email content is generated by EmailService
 */
public interface EmailMessage extends Message {

    EmailType getEmailType();
    /**
     * Account Information
     */
    String getAccountId();
    String getEmail();
    String getName();
    String getSource();

    @Override
    default MessageType getMessageType() {
        return getEmailType();
    }
}
