package com.fp.lambda.message;

import com.fp.lambda.enumeration.EmailType;
import software.amazon.awssdk.services.sqs.model.MessageAttributeValue;

import java.util.HashMap;
import java.util.Map;


/**
 * Email Message DTO for SQS communication.
 * Contains only business data, email content is generated by EmailService
 */
public interface EmailMessage extends Message {

    EmailType getEmailType();
    /**
     * Account Information
     */
    String getAccountId();

    String getEmail();

    String getName();

    @Override
    default MessageType getMessageType() {
        return getEmailType();
    }



    @Override
    default Map<String, MessageAttributeValue> getMessageAttributes(){
        return null;
    }
}
