management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints
  endpoint:
    health:
      show-details: always
  server:
    port: 10000  # management port
    address: 127.0.0.1  # Only bind to localhost for security

server:
  port: 8080



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web.client: DEBUG
    com.fp: ${APP_LOGGING_LEVEL:INFO} # Default to INFO if APP_LOG_LEVEL is not set
    com.fp.auth.filter.RequestLoggingFilter: ${REQUEST_LOGGING_LEVEL:INFO} # Default to DEBUG if REQUEST_LOGGING_LEVEL is not set

services:
  follow:
    enabled: true
    url: ${FOLLOW_SERVICE_URL:http://localhost:8081}


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha #Sort tags alphabetically
    operations-sorter: method #Sort operations by method name
    display-request-duration: true #Display request duration in the UI
    try-it-out-enabled: false #Fold "Try it out" feature as default


fp:
  jwt:
    secret: ${JWT_SECRET}
  aws:
    dynamodb:
      enabled: true
      region: ${AWS_REGION}
      table-prefix: ${DYNAMODB_TABLE_PREFIX}
      table-suffix: ${DYNAMODB_TABLE_SUFFIX}
    sqs:
      region: ${AWS_REGION}
      email-queue:
        queue-url: ${SQS_EMAIL_QUEUE_URL}
      dead-letter-queue:
        queue-url: ${SQS_DEAD_LETTER_QUEUE_URL}
      follower-notification-queue:
        queue-url: ${SQS_FOLLOWER_NOTIFICATION_QUEUE_URL}