AWSTemplateFormatVersion: '2010-09-09'
Description: 'Financial Pulse RDS PostgreSQL Database - Free Tier Compatible'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, test, prod]

  VPCStackName:
    Type: String
    Default: fp-vpc-dev
    Description: VPC Stack name

  SecurityStackName:
    Type: String
    Default: fp-security-dev
    Description: Security Stack name

  MasterUsername:
    Type: String
    Default: postgres
    Description: Master username for RDS

  MasterPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Master password for RDS instance

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro    # Free Tier eligible
      - db.t2.micro
    Description: Database instance class (db.t3.micro is Free Tier eligible)

  AllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 20
    Description: Database storage in GB (20GB is Free Tier limit)

Resources:
  # DB Subnet Group
  DBPrivateSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private Subnet group for RDS PostgreSQL instance
      SubnetIds:
        - Fn::ImportValue: !Sub ${VPCStackName}-PrivateSubnet1Id
        - Fn::ImportValue: !Sub ${VPCStackName}-PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub fp-db-subnet-group-${Environment}
  DBPublicSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Public Subnet group for RDS PostgreSQL instance
      SubnetIds:
        - Fn::ImportValue: !Sub ${VPCStackName}-PublicSubnet1Id
        - Fn::ImportValue: !Sub ${VPCStackName}-PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub fp-db-subnet-group-${Environment}

  # RDS PostgreSQL Instance - Free Tier Optimized
  PostgreSQLDatabase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: !If [IsProduction, Snapshot, Delete]
    Properties:
      DBInstanceIdentifier: !Sub fp-postgres-${Environment}
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      EngineVersion: '17.4'  # Use supported version for Free Tier
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp2  # General Purpose SSD (Free Tier eligible)
      StorageEncrypted: !If [IsProduction, true, false]  # Disable encryption for Free Tier
      # Create default database
      DBName: postgres
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterPassword
      DBSubnetGroupName: !Ref DBPublicSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${SecurityStackName}-DatabaseSecurityGroupId
      PubliclyAccessible: true
      # Free Tier optimized settings
      BackupRetentionPeriod: !If [IsProduction, 7, 0]  # No backup for dev to save costs
      PreferredBackupWindow: !If [IsProduction, "03:00-04:00", !Ref AWS::NoValue]
      PreferredMaintenanceWindow: !If [IsProduction, "sun:04:00-sun:05:00", !Ref AWS::NoValue]
      DeletionProtection: !If [IsProduction, true, false]
      # Disable expensive features for Free Tier
      EnablePerformanceInsights: false
      MonitoringInterval: 0  # Disable enhanced monitoring
      MultiAZ: !If [IsProduction, true, false]  # Single AZ for Free Tier
      # Parameter group for optimization (optional)
      DBParameterGroupName: !If [IsProduction, !Ref PostgreSQLParameterGroup, !Ref AWS::NoValue]
      Tags:
        - Key: Name
          Value: !Sub fp-postgres-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: CostOptimized
          Value: FreeTier

  # Optional: Custom Parameter Group for production
  PostgreSQLParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Condition: IsProduction
    Properties:
      Description: Custom parameter group for PostgreSQL
      Family: postgres17
      Parameters:
        shared_preload_libraries: pg_stat_statements
        log_statement: all
        log_min_duration_statement: 1000
      Tags:
        - Key: Name
          Value: !Sub fp-postgres-params-${Environment}

Conditions:
  IsProduction: !Equals [!Ref Environment, 'prod']
  IsFreeTier: !And
    - !Equals [!Ref DBInstanceClass, 'db.t3.micro']
    - !Equals [!Ref AllocatedStorage, 20]

Outputs:
  DBEndpoint:
    Description: RDS PostgreSQL endpoint
    Value: !GetAtt PostgreSQLDatabase.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-DBEndpoint

  DBPort:
    Description: RDS PostgreSQL port
    Value: !GetAtt PostgreSQLDatabase.Endpoint.Port
    Export:
      Name: !Sub ${AWS::StackName}-DBPort

  MasterUsername:
    Description: Master username
    Value: !Ref MasterUsername
    Export:
      Name: !Sub ${AWS::StackName}-MasterUsername

  DatabaseName:
    Description: Default database name
    Value: postgres
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseName

  JDBCConnectionString:
    Description: JDBC connection string for applications
    Value: !Sub 'jdbc:postgresql://${PostgreSQLDatabase.Endpoint.Address}:${PostgreSQLDatabase.Endpoint.Port}/postgres'
    Export:
      Name: !Sub ${AWS::StackName}-JDBCConnectionString

  # Free Tier status indicator
  FreeTierEligible:
    Description: Indicates if this configuration is Free Tier eligible
    Value: !If [IsFreeTier, 'Yes', 'No']
    Export:
      Name: !Sub ${AWS::StackName}-FreeTierEligible

  # Cost estimation
  EstimatedMonthlyCost:
    Description: Estimated monthly cost
    Value: !If [IsFreeTier, '$0 (Free Tier)', '$15-30 (Paid Tier)']
    Export:
      Name: !Sub ${AWS::StackName}-EstimatedCost